# Generated by Django 2.2.2 on 2019-07-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookData',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PostData',
        ),
    ]
